 <form id="myForm" action="<?php  echo $this->basePath() ?>/auth/authenticate" method="post" >
<div class="text-center">
	<h3 class="page-header">Dexperien Login Page</h3>
</div>
<div class="form-group">
	<label class="control-label">Username</label>
	<input type="text" class="form-control" name="username" />
</div>
<div class="form-group">
	<label class="control-label">Password</label>
	<input type="password" class="form-control" name="password" />
</div>
<div class="text-center">
	<input type="submit" name="submit" class="btn btn-primary" value="Sign in" />
	
</div>
</form>