<?php
	$page_title = 'Lead';
    if(isset($model["idLead"]))
	    $page_function = 'Edit';
    else
        $page_function = 'Add';
	$this->headTitle($page_title.' '.$page_function);

?>
<div class="row">
    <div id="breadcrumb" class="col-xs-12">
        <ol class="breadcrumb">
            <li><a href="<?php echo $this->basePath() ?>">Dashboard</a></li>
            <li><a href="<?php echo $this->basePath() ?>/lead/index"><?php echo $page_title; ?></a></li>
            <li><a href="#"><?php echo $page_function; ?></a></li>
        </ol>
    </div>
</div>
<div class="row">
	<form id="defaultForm" action="<?php  echo $this->basePath() ?>/lead/save" method="post" class="form-horizontal">
		<div class="col-xs-12 col-sm-12">
			<div class="form-group" style="text-align: right;padding: 0 15px;">
				<a href="<?php  echo $this->basePath() ?>/lead/index" class="btn btn-default btn-label-left"><span><i class="fa fa-clock-o txt-danger"></i></span>Cancel</a>
				<button type="submit" class="btn btn-primary btn-label-left"><span><i class="fa fa-clock-o"></i></span>Submit</button>
			</div>
		</div>
		<div class="col-xs-12 col-sm-12">
			<div class="box">
				<div class="box-header">
					<div class="box-name">
						<i class="fa fa-pencil"></i>
						 <span>Lead</span>
					</div>
					<div class="box-icons">
						<a class="collapse-link">
							<i class="fa fa-chevron-up"></i>
						</a>
						<a class="expand-link">
							<i class="fa fa-expand"></i>
						</a>
						<a class="close-link">
							<i class="fa fa-times"></i>
						</a>
					</div>
					<div class="no-move"></div>
				</div>			
				<div class="box-content">				
					<fieldset>	
						<div class="form-group hidden">
							<label class="col-sm-3 control-label">ID</label>
							<div class="col-sm-5">
								<input type="text" name="idLead" id="idLead" class="form-control" readonly="readonly"
									   value="<?php echo array_key_exists('idLead', $model) ? ($model["idLead"]) : "0" ?>" />
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">ID No</label>
							<div class="col-sm-5">
								<input type="text" class="form-control" name="strIdNo" value="<?php echo array_key_exists('strIdNo', $model) ? ($model["strIdNo"]) : "" ?>"/>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">First Name</label>
							<div class="col-sm-5">
								<input type="text" class="form-control" name="strFirstName" value="<?php echo array_key_exists('strFirstName', $model) ? ($model["strFirstName"]) : "" ?>"/>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Last Name</label>
							<div class="col-sm-5">
								<input type="text" class="form-control" name="strLastName" value="<?php echo array_key_exists('strLastName', $model) ? ($model["strLastName"]) : "" ?>"/>
							</div>
						</div>
						
						<div class="form-group">
							<label class="col-sm-3 control-label">Email</label>
							<div class="col-sm-5">
								<input type="text" class="form-control" name="strEmail" value="<?php echo array_key_exists('strEmail', $model) ? ($model["strEmail"]) : "" ?>"/>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Mobile</label>
							<div class="col-sm-5">
								<input type="text" class="form-control" name="strMobileNo"  value="<?php echo array_key_exists('strMobileNo', $model) ? ($model["strMobileNo"]) : "" ?>"/>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Source</label>
							<div class="col-sm-5">
								<select id="intSource" name="intSource" class="populate placeholder">
									<option value="">Select</option>
									<option value="1" <?php echo array_key_exists('intSource', $model) ? $model["intSource"] == 1 ? "selected": "" : "" ?> >Manual Upload</option>
									<option value="2" <?php echo array_key_exists('intSource', $model) ? $model["intSource"] == 2 ? "selected": "" : "" ?> >Web Advert</option>
									<option value="3" <?php echo array_key_exists('intSource', $model) ? $model["intSource"] == 3 ? "selected": "" : "" ?> >Survey</option>
									
								</select>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Existing Contact ID</label>
							<div class="col-sm-5">
								<input type="text" class="form-control" name="strAppKey" />
							</div>
						</div>	
						<div class="form-group">
							<label class="col-sm-3 control-label">Campaign</label>
							<div class="col-sm-5">
								<input type="text" class="form-control" name="strCampaignCode" value="<?php echo array_key_exists('strCampaignCode', $model) ? ($model["strCampaignCode"]) : "" ?>"/>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Afiliate</label>
							<div class="col-sm-5">
								<input type="text" class="form-control" name="strAffilliateCode" value="<?php echo array_key_exists('strAffilliateCode', $model) ? ($model["strAffilliateCode"]) : "" ?>">
							</div>
						</div>
						<br />
						<div class="form-group">
							<label class="col-sm-3 control-label">Email Consent</label>
							<div class="col-sm-5">
								<div class="toggle-switch toggle-switch-success">
									<label>
										<input type="checkbox" name="intEmailConsent" id="intEmailConsent" <?php echo array_key_exists('intEmailConsent', $model) ? (int)$model["intEmailConsent"] == 1 ? "checked": "" : "" ?>>
										<div class="toggle-switch-inner"></div>
										<div class="toggle-switch-switch"><i class="fa fa-check"></i></div>
									</label>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Email Status</label>
							<div class="col-sm-5">
								<select id="intEmailStatus" name="intEmailStatus" class="populate placeholder">
									<option value="">Select</option>
									<option value="0" <?php echo array_key_exists('intEmailStatus', $model) ? $model["intEmailStatus"] == 0 ? "selected": "" : "" ?> >Pending</option>
									<option value="1" <?php echo array_key_exists('intEmailStatus', $model) ? $model["intEmailStatus"] == 1 ? "selected": "" : "" ?> >Email Sent</option>
									<option value="2" <?php echo array_key_exists('intEmailStatus', $model) ? $model["intEmailStatus"] == 2 ? "selected": "" : "" ?> >Email Delivered</option>
									<option value="3" <?php echo array_key_exists('intEmailStatus', $model) ? $model["intEmailStatus"] == 3 ? "selected": "" : "" ?> >Email Opened</option>
									<option value="5" <?php echo array_key_exists('intEmailStatus', $model) ? $model["intEmailStatus"] == 4 ? "selected": "" : "" ?> >Email Bounced</option>
								</select>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">SMS Consent</label>
							<div class="col-sm-5">
								<div class="toggle-switch toggle-switch-success">
									<label>
										<input type="checkbox" name="intMobileConsent" id="intMobileConsent" <?php echo array_key_exists('intMobileConsent', $model) ? (int)$model["intMobileConsent"] == 1 ? "checked": "" : "" ?>>
										<div class="toggle-switch-inner"></div>
										<div class="toggle-switch-switch"><i class="fa fa-check"></i></div>
									</label>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Mobile Status</label>
							
								<div class="col-sm-5">
								<select id="intSMSStatus" name="intSMSStatus" class="populate placeholder">
									<option value="">Select</option>
									<option value="1" <?php echo array_key_exists('intSMSStatus', $model) ? $model["intSMSStatus"] == 0 ? "selected": "" : "" ?>>Pending</option>
									<option value="2" <?php echo array_key_exists('intSMSStatus', $model) ? $model["intSMSStatus"] == 1 ? "selected": "" : "" ?>>SMS Sent</option>
									<option value="3" <?php echo array_key_exists('intSMSStatus', $model) ? $model["intSMSStatus"] == 2 ? "selected": "" : "" ?>>Response Received</option>
									
								</select>
							</div>
						</div>
						<br />
						<div class="form-group">
							<label class="col-sm-3 control-label">Status</label>
							
								<div class="col-sm-5">
								<select id="intStatus" name="intStatus" class="populate placeholder">
									<option value="">Select</option>
									<option value="1" <?php echo array_key_exists('intStatus', $model) ? $model["intStatus"] == 1 ? "selected": "" : "" ?>>Active</option>
									<option value="0" <?php echo array_key_exists('intStatus', $model) ? $model["intStatus"] == 0 ? "selected": "" : "" ?>>InActive</option>
								
								</select>
							</div>
						</div>
					</fieldset>
				</div>			
			</div>
		</div>
		
		
		<div class="col-xs-12 col-sm-12">
			<div class="form-group" style="text-align: left;padding: 0 15px;">
				<a href="<?php  echo $this->basePath() ?>/lead/index" class="btn btn-default btn-label-left"><span><i class="fa fa-clock-o txt-danger"></i></span>Cancel</a>
				<button type="submit" class="btn btn-primary btn-label-left"><span><i class="fa fa-clock-o"></i></span>Submit</button>
			</div>
		</div>
	</form>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        // add the rule here
        $.validator.addMethod("valueNotEquals", function(value, element, arg){
            return arg != value;
        }, "Please select an option");
        $('#defaultForm').validate({
            rules: {
				strIdNo: {
                    required: true,
                    maxlength: 200
                },
                strFirstName: {
                    required: true,
                    maxlength: 200
                },
				strEmail: {
                    required: true,
                    maxlength: 200
                },
				strMobileNo: {
                    required: true,
                    maxlength: 200
                },
				intSource: {
					 valueNotEquals:""
				},
				intStatus: {
					 valueNotEquals:""
				},
            },
            errorPlacement: function(error, element) {
                error.appendTo(element.parent());
            }
        });
		LoadSelect2Script(DemoSelect2);
		
    });
	function DemoSelect2(){
			$('#intSource').select2();
			$('#intEmailStatus').select2();	
			$('#intSMSStatus').select2();	
			$('#intStatus').select2();	
	}
</script>