<?php 
	$page_title = 'Lead';
	$page_function = 'List';
	$this->headTitle($page_title.' '.$page_function);
	
	//check access right
	$intUserType = $_SESSION['intUserType'];
	
	$rightView = 0;
	$rightAdd = 0;
	$rightEdit = 0;
	$rightDel = 0;
	foreach($accessRight as $access):
		$rightView  = (int)$access["intView"];
		$rightAdd  = (int)$access["intAdd"];
		$rightEdit  = (int)$access["intEdit"];
		$rightDel  = (int)$access["intDelete"];
	endforeach;
?>
<div class="row">
    <div id="breadcrumb" class="col-xs-12">
        <ol class="breadcrumb">
            <li><a href="<?php echo $this->basePath() ?>">Dashboard</a></li>
            <li><a href="<?php echo $this->basePath() ?>/entity/index"><?php echo $page_title; ?></a></li>
            <li><a href="#"><?php echo $page_function; ?></a></li>
        </ol>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
         <div class="toolbar">
            <div class="pull-right">
                <a id="addItem" class="btn-add btn btn-default" href="<?php echo $this->basePath() . "/lead/edit/id/0"; ?>">Add</a>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="box">
            <div class="box-header">
                <div class="box-name">
                    <i class="fa fa-users"></i>
                    <span><?php echo $page_title.' '.$page_function; ?></span>
                </div>
                <div class="box-icons">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="expand-link">
                        <i class="fa fa-expand"></i>
                    </a>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
                <div class="no-move"></div>
            </div>
            <div class="box-content no-padding">
                <table class="table table-bordered table-striped table-hover table-heading table-datatable" id="datatable-1">
                    <thead>
                        <tr>
                            <th>Name</th>
						    <th>Email</th>
							<th>Mobile</th>
						    <th>Source</th>
							<th>Status</th>
						    <th></th>
                        </tr>
                    </thead>
                    <tbody>
                	<!-- Start: list_row -->
                	<?php foreach($data as $item) : ?>
						<tr class="table-body">
						    <td class="table-body-row name column-left">
								<a  rel="tooltip" data-placement="top" data-original-title=" Edit " href="<?php echo $this->url('home/default', array('controller'=>'lead','action' => 'edit', 'id' => $item["idLead"] )) ?>">
									<?php echo $this->escapeHtml($item["strFirstName"]) . " " .$this->escapeHtml($item["strLastName"]);?>
								</a>
							</td>
						    <td class="table-body-row name column-left">
								
									<?php echo $this->escapeHtml($item["strEmail"]);?>
								
							</td>
							<td class="table-body-row name column-left"><?php echo $this->escapeHtml($item["strMobileNo"]);?></td>
						    <td class="table-body-row name column-left">
								<?php 
									$intSource = $this->escapeHtml($item["intSource"]);
									
									switch ((int)$intSource) {
										case 1:
											echo "Manual Upload";
											break;
										case 2:
											echo "Web Advert";
											break;
										case 3:
											echo "Survey";
											break;
									}
								?>
							</td>
							<td class="table-body-row name column-left">
								<?php 
									$intStatus = $this->escapeHtml($item["intStatus"]);
									
									switch ((int)$intStatus) {
										case 1:
											echo "Active";
											break;
										case 2:
											echo "InActive";
											break;
									}
								?>
							</td>
						    <td class="table-body-row last-column">
						    	<div class="btn-group btn-control"> 
	                                <a class="btn btn-default edit" rel="tooltip" data-placement="top" data-original-title=" Edit " href="<?php echo $this->url('home/default', array('controller'=>'lead','action' => 'edit', 'id' => $item["idLead"] )) ?>">
	                                    Edit
	                                </a>
									<?php if((int)$intUserType == 0 ): ?>
	                                <a class="btn btn-default delete" rel="tooltip" data-placement="top" data-original-title=" Delete " href="<?php echo $this->url('home/default', array('controller'=>'lead','action' => 'delete', 'id' => $item["idLead"] )) ?>">Delete
	                                </a>
									<?php endif; ?>
	                            </div>
						    </td>
						</tr>
					<?php endforeach; ?>
                    <!-- End: list_row -->
                    </tbody>
                    <tfoot>
                        <tr>
							<th>Entity Id</th>
						    <th>Entity Name</th>
							<th>Email</th>
						    <th>Website Name</th>
							<th>Mobile No</th>
						    <th></th>
                        </tr>
                    </tfoot>
                </table>
                </div>
        </div>
    </div>
</div>


<div class="clear"></div>

<script type="text/javascript">
// Run Datables plugin and create 3 variants of settings
function AllTables(){
    TestTable1();
    LoadSelect2Script(MakeSelect2);
}
function MakeSelect2(){
    $('select').select2();
    $('.dataTables_filter').each(function(){
        $(this).find('label input[type=text]').attr('placeholder', 'Search');
    });
}
$(document).ready(function() {
    // Load Datatables and run plugin on tables 
    LoadDataTablesScripts(AllTables);
    // Add Drag-n-Drop feature
    WinMove();
});
</script>