<?php
	$page_title = 'Conversion Rule';
    if(isset($model["idConversionRule"]))
	    $page_function = 'Edit';
    else
        $page_function = 'Add';
	$this->headTitle($page_title.' '.$page_function);

?>
<div class="row">
    <div id="breadcrumb" class="col-xs-12">
        <ol class="breadcrumb">
            <li><a href="<?php echo $this->basePath() ?>">Dashboard</a></li>
            <li><a href="<?php echo $this->basePath() ?>/lead-conversion-rule/index"><?php echo $page_title; ?></a></li>
            <li><a href="#"><?php echo $page_function; ?></a></li>
        </ol>
    </div>
</div>
<div class="row">
	<form id="defaultForm" action="<?php  echo $this->basePath() ?>/lead-conversion-rule/save" method="post" class="form-horizontal">
		<div class="col-xs-12 col-sm-12">
			<div class="form-group" style="text-align: right;padding: 0 15px;">
				<a href="<?php  echo $this->basePath() ?>/lead-conversion-rule/index" class="btn btn-default btn-label-left"><span><i class="fa fa-clock-o txt-danger"></i></span>Cancel</a>
				<button type="submit" class="btn btn-primary btn-label-left"><span><i class="fa fa-clock-o"></i></span>Submit</button>
			</div>
		</div>
		<div class="col-xs-12 col-sm-12">
			<div class="box">
				<div class="box-header">
					<div class="box-name">
						<i class="fa fa-pencil"></i>
						 <span>Conversion Rule</span>
					</div>
					<div class="box-icons">
						<a class="collapse-link">
							<i class="fa fa-chevron-up"></i>
						</a>
						<a class="expand-link">
							<i class="fa fa-expand"></i>
						</a>
						<a class="close-link">
							<i class="fa fa-times"></i>
						</a>
					</div>
					<div class="no-move"></div>
				</div>			
				<div class="box-content">				
					<fieldset>	
						<div class="form-group hidden">
							<label class="col-sm-3 control-label">ID</label>
							<div class="col-sm-5">
								<input type="text" name="idConversionRule" id="idConversionRule" class="form-control" readonly="readonly"
									   value="<?php echo array_key_exists('idConversionRule', $model) ? ($model["idConversionRule"]) : "0" ?>" />
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Id Entity</label>
							<div class="col-sm-5">
								<input type="text" class="form-control" name="idEntity" value="<?php echo array_key_exists('idEntity', $model) ? ($model["idEntity"]) : "" ?>"/>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">ConversionRule Name</label>
							<div class="col-sm-5">
								<input type="text" class="form-control" name="strConversionRuleName" value="<?php echo array_key_exists('strConversionRuleName', $model) ? ($model["strConversionRuleName"]) : "" ?>"/>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Type</label>
							<div class="col-sm-5">
							
								<select id="intType" name="intType" class="form-control">
									<option value="">Select</option>
									<option value="1" <?php echo array_key_exists('intType', $model) ? $model["intType"] == 1 ? "selected": "" : "" ?> >General</option>
									<option value="2" <?php echo array_key_exists('intType', $model) ? $model["intType"] == 2 ? "selected": "" : "" ?> >Campaign</option>
									<option value="3" <?php echo array_key_exists('intType', $model) ? $model["intType"] == 2 ? "selected": "" : "" ?> >Advertisement</option> 
								</select>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Campaign</label>
							<div class="col-sm-5">
								<input type="text" class="form-control" name="strCampaignCode" value="<?php echo array_key_exists('strCampaignCode', $model) ? ($model["strCampaignCode"]) : "" ?>"/>
							</div>
						</div>
						<br />
						<div class="form-group">
							<h4 class="col-sm-3 control-label">Convert Lead When</h4>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Email Consent </label>
							<div class="col-sm-5">
								<select id="intEmailConsent" name="intEmailConsent" class="form-control">
									<option value="">Select</option>
									<option value="1" <?php echo array_key_exists('intEmailConsent', $model) ? $model["intEmailConsent"] == 1 ? "selected": "" : "" ?> >Yes</option>
									<option value="2" <?php echo array_key_exists('intEmailConsent', $model) ? $model["intEmailConsent"] == 2 ? "selected": "" : "" ?> >Any</option>
								</select>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Email Status</label>
							<div class="col-sm-5">
								
								<select id="intEmailStatus" name="intEmailStatus" class="form-control">
									<option value="">Select</option>
									<option value="0" <?php echo array_key_exists('intEmailStatus', $model) ? $model["intEmailStatus"] == 0 ? "selected": "" : "" ?> >Pending</option>
									<option value="1" <?php echo array_key_exists('intEmailStatus', $model) ? $model["intEmailStatus"] == 1 ? "selected": "" : "" ?> >Email Sent</option>
									<option value="2" <?php echo array_key_exists('intEmailStatus', $model) ? $model["intEmailStatus"] == 2 ? "selected": "" : "" ?> >Email Delivered</option>
									<option value="3" <?php echo array_key_exists('intEmailStatus', $model) ? $model["intEmailStatus"] == 3 ? "selected": "" : "" ?> >Email Opened</option>
									<option value="4" <?php echo array_key_exists('intEmailStatus', $model) ? $model["intEmailStatus"] == 4 ? "selected": "" : "" ?> >Email Clicked</option>
								</select>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label"></label>
							<div class="col-sm-2">
								<select id="EmailSMSOperator" name="EmailSMSOperator" class="form-control">
									<option value="">OR / AND</option>
									<option value="1" <?php echo array_key_exists('EmailSMSOperator', $model) ? $model["EmailSMSOperator"] == 1 ? "selected": "" : "" ?> >And</option>
									<option value="2" <?php echo array_key_exists('EmailSMSOperator', $model) ? $model["EmailSMSOperator"] == 2 ? "selected": "" : "" ?> >Or</option>
								</select>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">SMS Consent</label>
							<div class="col-sm-5">
								<select id="intSMSConsent" name="intSMSConsent" class="form-control">
									<option value="">Select</option>
									<option value="1" <?php echo array_key_exists('intSMSConsent', $model) ? $model["intSMSConsent"] == 1 ? "selected": "" : "" ?> >Yes</option>
									<option value="2" <?php echo array_key_exists('intSMSConsent', $model) ? $model["intSMSConsent"] == 2 ? "selected": "" : "" ?> >Any</option>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<label class="col-sm-3 control-label">Mobile Status</label>
							<div class="col-sm-5">
							
								<select id="intSMSStatus" name="intSMSStatus" class="form-control">
									<option value="">Select</option>
									<option value="0" <?php echo array_key_exists('intSMSStatus', $model) ? $model["intSMSStatus"] == 0 ? "selected": "" : "" ?> >Pending</option>
									<option value="1" <?php echo array_key_exists('intSMSStatus', $model) ? $model["intSMSStatus"] == 1 ? "selected": "" : "" ?> >SMS Sent</option>
									<option value="2" <?php echo array_key_exists('intSMSStatus', $model) ? $model["intSMSStatus"] == 2 ? "selected": "" : "" ?> >Response Received</option>
									 
								</select>
							</div>
						</div>
						<br />
						<div class="form-group">
							<label class="col-sm-3 control-label">Status</label>
							<div class="col-sm-5">							
								<select id="intStatus" name="intStatus" class="form-control">
									<option value="">Select</option>
									<option value="1" <?php echo array_key_exists('intStatus', $model) ? $model["intStatus"] == 1 ? "selected": "" : "" ?> >Active</option>
									<option value="0" <?php echo array_key_exists('intStatus', $model) ? $model["intStatus"] == 0 ? "selected": "" : "" ?> >InActive</option>
								</select>
							</div>
						</div>
						
					</fieldset>
				</div>			
			</div>
		</div>
		
		
		<div class="col-xs-12 col-sm-12">
			<div class="form-group" style="text-align: left;padding: 0 15px;">
				<a href="<?php  echo $this->basePath() ?>/lead-conversion-rule/index" class="btn btn-default btn-label-left"><span><i class="fa fa-clock-o txt-danger"></i></span>Cancel</a>
				<button type="submit" class="btn btn-primary btn-label-left"><span><i class="fa fa-clock-o"></i></span>Submit</button>
			</div>
		</div>
	</form>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        // add the rule here
        $.validator.addMethod("valueNotEquals", function(value, element, arg){
            return arg != value;
        }, "Please select an option");
        $('#defaultForm').validate({
            rules: {
				strCampaignCode: {
                    required: true,
                    maxlength: 200
                },
				intType: {
					 valueNotEquals:""
				},
				intStatus: {
					 valueNotEquals:""
				},
				EmailSMSOperator: {
					 valueNotEquals:""
				}
            },
            errorPlacement: function(error, element) {
                error.appendTo(element.parent());
            }
        });
		
		
    });
	
</script>