<div id="sidebar-left" class="col-xs-2 col-sm-2">
    <ul class="nav main-menu">
        <li>
            <a href="#" class="active ajax-link">
                <i class="fa fa-dashboard"></i>
                <span class="hidden-xs">Dashboard</span>
            </a>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle">
                <i class="fa fa-picture-o"></i>
                 <span class="hidden-xs">System</span>
            </a>
            <ul class="dropdown-menu">
                <li class=""><a class="" href="#">User Profile</a></li>
                <li class=""><a class="" href="<?php echo $this->basePath('user-type') ?>">User Type</a></li>
            </ul>
        </li>
    </ul>
</div>