<?php
	$page_title = 'User';
    if(isset($model["idUser"]))
	    $page_function = 'Edit';
    else
        $page_function = 'Add';
	$this->headTitle($page_title.' '.$page_function);
	
	//check access right
	$rightView = 0;
	$rightAdd = 0;
	$rightEdit = 0;
	$rightDel = 0;
	foreach($accessRight as $access):
		$rightView  = (int)$access["intView"];
		$rightAdd  = (int)$access["intAdd"];
		$rightEdit  = (int)$access["intEdit"];
		$rightDel  = (int)$access["intDelete"];
	endforeach;
?>
<div class="row">
    <div id="breadcrumb" class="col-xs-12">
        <ol class="breadcrumb">
            <li><a href="<?php echo $this->basePath() ?>">Dashboard</a></li>
            <li><a href="<?php echo $this->basePath() ?>/entity/index"><?php echo $page_title; ?></a></li>
            <li><a href="#"><?php echo $page_function; ?></a></li>
        </ol>
    </div>
</div>
<style type="text/css">
	.table{margin-bottom:0;}
	.table.beauty-table.table-hover tr td{width:300px;}
	.table.beauty-table.table-hover tr td:first-child{width:200px;}
	.table.beauty-table.table-hover tr td:last-child{width:500px;}
</style>
<div class="row">
	<form id="defaultForm" action="<?php  echo $this->basePath() ?>/entity-user/save" method="post" class="form-horizontal">
		<div class="col-xs-12 col-sm-12">
			<div class="form-group" style="text-align: right;padding: 0 15px;">
				<a href="<?php  echo $this->basePath() ?>/entity-user" class="btn btn-default btn-label-left"><span><i class="fa fa-clock-o txt-danger"></i></span>Cancel</a>
				<?php if($rightAdd == 1 && $rightEdit == 1): ?>
				<button type="submit" class="btn btn-primary btn-label-left"><span><i class="fa fa-clock-o"></i></span>Submit</button>
				<?php endif ?>
			</div>
		</div>
		<div class="col-xs-12 col-sm-12">
			<div class="box">
				<div class="box-header">
					<div class="box-name">
						<i class="fa fa-pencil"></i>
						 <span>User Detail</span>
					</div>
					<div class="box-icons">
						<a class="collapse-link">
							<i class="fa fa-chevron-up"></i>
						</a>
						<a class="expand-link">
							<i class="fa fa-expand"></i>
						</a>
						<a class="close-link">
							<i class="fa fa-times"></i>
						</a>
					</div>
					<div class="no-move"></div>
				</div>			
				<div class="box-content">				
					<fieldset>	
						<div class="form-group hidden">
							<label class="col-sm-3 control-label">idUser</label>
							<div class="col-sm-5">
								<input type="text" name="idUser" id="idUser" class="form-control" readonly="readonly"
									   value="<?php echo array_key_exists('idUser', $model) ? ($model["idUser"]) : "0" ?>" />
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Entity</label>
							<div class="col-sm-5">
								<select id="idEntity" name="idEntity" class="populate placeholder">
									<option value="-1">-- Select Entity --</option>
									<?php 
										$idEntity = $model["idEntity"];
										foreach($data_entity as $item) : 
											if($idEntity == $item['idEntity'])
												echo '<option value="'.$item['idEntity'].'" selected >'.$item['strName'].'</option>';
											else
												echo '<option value="'.$item['idEntity'].'" >'.$item['strName'].'</option>';
									
										endforeach; 
									?>
								</select>
					
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Name</label>
							<div class="col-sm-5">
								<input type="text" class="form-control" name="strName" value="<?php echo array_key_exists('strName', $model) ? ($model["strName"]) : "" ?>"/>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Login Name</label>
							<div class="col-sm-5">
								<input type="text" class="form-control" name="strLoginId" value="<?php echo array_key_exists('strLoginId', $model) ? ($model["strLoginId"]) : "" ?>" <?php echo $page_function =="Edit" ? "readonly": "" ?>/>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Email</label>
							<div class="col-sm-5">
								<input type="text" class="form-control" name="strEmail" value="<?php echo array_key_exists('strEmail', $model) ? ($model["strEmail"]) : "" ?>"/>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Mobile No</label>
							<div class="col-sm-5">
								<input type="text" class="form-control" name="strMobileNo" placeholder="" value="<?php echo array_key_exists('strMobileNo', $model) ? ($model["strMobileNo"]) : "" ?>"/>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Android Id</label>
							<div class="col-sm-5">
								<input type="text" class="form-control" name="strAndroidId" value="<?php echo array_key_exists('strAndroidId', $model) ? ($model["strAndroidId"]) : "" ?>"/>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">iOS Id</label>
							<div class="col-sm-5">
								<input type="text" class="form-control" name="striOSId" value="<?php echo array_key_exists('striOSId', $model) ? ($model["striOSId"]) : "" ?>"/>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Password</label>
							<div class="col-sm-5">
								<input type="password" class="form-control" name="strPassword"  />
							</div>
						</div>	
						<div class="form-group">
							<label class="col-sm-3 control-label">Status</label>
							<div class="col-sm-5">
								<select id="intStatus" name="intStatus" class="populate placeholder">		
									<option value="-1">-- Select Status --</option>
									<option value="0" <?php echo array_key_exists('intStatus', $model) ? $model["intStatus"] == 0 ? "selected": "" : "" ;?> >Inactive</option>
									<option value="1" <?php echo array_key_exists('intStatus', $model) ? $model["intStatus"] == 1 ? "selected": "" : "" ; ?> >Active</option>
								</select>
							</div>
						</div>
						<?php  $chkUserType = (int)$UserType;?>
							<div class="form-group">
								<label class="col-sm-3 control-label">Is Supper Admin</label>
								<div class="col-sm-5">
									<select id="intUserType" name="intUserType" class="populate placeholder">		
											<option value="-1">-- Select Status --</option>
											<?php if($chkUserType == 0): ?>
											<option value="0" <?php echo array_key_exists('intUserType', $model) ? $model["intUserType"] == 0 ? "selected": "" : "" ;?> >Supper Admin</option>
											<?php endif; ?>
											<?php if($chkUserType == 0 || $chkUserType == 1): ?>
											<option value="1" <?php echo array_key_exists('intUserType', $model) ? $model["intUserType"] == 1 ? "selected": "" : "" ; ?> >Entity Admin</option>
											<?php endif; ?>
											<?php if($chkUserType == 0 || $chkUserType == 1 || $chkUserType == 2) : ?>
											<option value="2" <?php echo array_key_exists('intUserType', $model) ? $model["intUserType"] == 2 ? "selected": "" : "" ; ?> >Enity</option>
											<?php endif; ?>
									</select>
								</div>								
							</div>
						
						
					</fieldset>
			<?php if($chkUserType != 2): ?>
					<fieldset>
						<legend>Access</legend>
						<input type="hidden" name="access" id="access" /><br />
						<input type="hidden" name="idUser" id="idUser" value="<?php echo array_key_exists('idUser', $model) ? ($model["idUser"]) : "0" ?>" /><br />
						 <?php 
							foreach($data_module_root as $itemRoot) : 
								$moduleID = $itemRoot["idModule"];
								$moduleName = $itemRoot["strModuleName"];
								$moduleURL = $itemRoot["strModuleUrl"];
								$tblChildrenModule = $this_controller->getChildModuleAction($moduleID);
						?>
						<table class="table beauty-table table-hover">	
							<tbody>
						<?php
								$i = 1;
								foreach($tblChildrenModule as $itemChilren):
									$childModuleID = $itemChilren["idModule"];
									$childModuleName = $itemChilren["strModuleName"];
									$childModuleURL = $itemChilren["strModuleUrl"];
									$UserId =  array_key_exists('idUser', $model) ? ($model["idUser"]) : "0";
									$tblModuleaccess = $this_controller->getUserPermission($UserId, $childModuleID);
									$intEdit = 0;
									$intAdd = 0;
									$intDelete = 0;
									$intView = 0;
									if(count($tblModuleaccess) > 0 ){
										foreach($tblModuleaccess as $itemModuleAccess){
											$intEdit = $itemModuleAccess["intEdit"];
											$intAdd = $itemModuleAccess["intAdd"];
											$intDelete = $itemModuleAccess["intDelete"];
											$intView = $itemModuleAccess["intView"];
										}
									}
						?>
							<tr>
							<td>
							<?php if($i == 1) { ?>
								<div class="checkbox-inline">
									 <label>
									 <input type="checkbox"  class="level1"> <?php echo $moduleName; ?>
									 <i class="fa fa-square-o "></i>
									 </label>
								</div>
							<?php } ?>
							</td>
							   <td>
								  <div class="checkbox-inline">
									 <label>
									 <input type="checkbox"  class="level2"> <?php echo $childModuleName; ?>
									 <i class="fa fa-square-o "></i>
									 </label>
								  </div>
							   </td>
							   <td class="access" module="<?php echo "module_".$childModuleID; ?>">
								  <div class="checkbox-inline">
									 <label>
									 <input type="checkbox" class="view level3" <?php echo $intView == "1" ? "checked" : "" ; ?> /> View
									 <i class="fa fa-square-o small"></i>
									 </label>
								  </div>
								  <div class="checkbox-inline">
									 <label>
									 <input type="checkbox" class="add level3" <?php echo $intAdd == "1" ? "checked" : "" ; ?> /> Add
									 <i class="fa fa-square-o small"></i>
									 </label>
								  </div>
								  <div class="checkbox-inline">
									 <label>
									 <input type="checkbox" class="edit level3" <?php echo $intEdit == "1" ? "checked" : "" ; ?> /> Edit
									 <i class="fa fa-square-o small"></i>
									 </label>
								  </div>
								  <div class="checkbox-inline">
									 <label>
									 <input type="checkbox" class="level3 delete" <?php echo $intDelete == "1" ? "checked" : "" ; ?> /> Delete
									 <i class="fa fa-square-o small"></i>
									 </label>
								  </div>
							   </td>
							</tr>
						<?php
									$i++;
								endforeach;
						?>
							</tbody>
						</table>	
							
						<?php											
							endforeach;
						 ?>
					</fieldset>
			<?php endif; ?>
				</div>			
			</div>
		</div>
		<div class="col-xs-12 col-sm-12">
			<div class="form-group" style="text-align: left;padding: 0 15px;">
				<a href="<?php  echo $this->basePath() ?>/entity-user" class="btn btn-default btn-label-left"><span><i class="fa fa-clock-o txt-danger"></i></span>Cancel</a>
				<?php if($rightAdd == 1 && $rightEdit == 1): ?>
				<button type="submit" class="btn btn-primary btn-label-left"><span><i class="fa fa-clock-o"></i></span>Submit</button>
				<?php endif; ?>
			</div>
		</div>
	</form>
</div>
<script type="text/javascript">
    $(document).ready(function() {     
        $.validator.addMethod("valueNotEquals", function(value, element, arg){
            return arg != value;
        }, "Please select an option");
        $('#defaultForm').validate({
            rules: {
                strName: {
                    required: true,
                    maxlength: 200
                },
				strLoginId: {
                    required: true,
                    maxlength: 200
                },
				strEmail : {
                    required: true,
                    maxlength: 200
                },
            },
            errorPlacement: function(error, element) {
                error.appendTo(element.parent());
            }
        });
		
		LoadSelect2Script(DemoSelect2);
    });
	
	// Run Select2 plugin on elements
	function DemoSelect2(){
		$('#intStatus').select2();
		$('#idEntity').select2();	
		$('#intUserType').select2();	
		
	}

</script>
 <script type="text/javascript">
         $(document).ready(function(){
         	$(".btn-primary").click(function(){
         		var accessModule = "{";
         		var countAccess = $("td.access").length;			
         		var i = 1;
         		$("td.access").each(function(){
         			var moduleName = $(this).attr("module");
         			var e_view = $(this).find('input[type="checkbox"].view');
         			var e_add = $(this).find("input[type='checkbox'].add");
         			var e_edit = $(this).find("input[type='checkbox'].edit");
         			var e_delete = $(this).find("input[type='checkbox'].delete");				
         			var view = $(e_view).is(":checked") ? "1" : "0";
         			var add = $(e_add).is(":checked") ? "1" : "0";
         			var edit = $(e_edit).is(":checked") ? "1" : "0";
         			var del = $(e_delete).is(":checked") ? "1" : "0";
         			var accessThisModule = "\"" + moduleName + "\" : {\"edit\":\""+edit+"\",\"add\":\""+add+"\",\"view\":\""+view+"\",\"del\":\""+del+"\"} ";
         			if(i < countAccess) accessThisModule = accessThisModule + " , ";
         			accessModule = accessModule + accessThisModule;
         			i = i + 1;
         		})
         		accessModule = accessModule + "}";			
         		$("#access").val(accessModule);
				
         	})
         	$("input[type='checkbox'].level1").click(function(){
         		var chk = $(this).is(":checked");
         		var children = $(this).parent("label").parent("div").parent("td").parent("tr").parent("tbody").find("input[type='checkbox']");			
         		$(children).prop('checked', chk);
         	});
         	$("input[type='checkbox'].level2").click(function(){
         		var chk = $(this).is(":checked");
         		var children = $(this).parent("label").parent("div").parent("td").parent("tr").find("input[type='checkbox']:not('.level1')");			
         		$(children).prop('checked', chk);
				//check if not all level1 checked then the parent not check
				var level2 = $(this).parent("label").parent("div").parent("td").parent("tr").parent("tbody").find("input[type='checkbox'].level2");	
				var level1 = $(this).parent("label").parent("div").parent("td").parent("tr").parent("tbody").find("input[type='checkbox'].level1");				
				var chklevel1 = true;
				$(level2).each(function(){					
         			var chkThis = $(this).is(":checked") ? true : false;	
					if(!chkThis) { 
						chklevel1 = false; 
					}
         		});
				$(level1).prop('checked', chklevel1);						
         	});
			$("td.access input[type='checkbox']").click(function(){
				var level2 = $(this).parent("label").parent("div").parent("td").parent("tr").find("input[type='checkbox'].level2");	
				var level1 = $(this).parent("label").parent("div").parent("td").parent("tr").parent("tbody").find("input[type='checkbox'].level1");	
				var chk = $(this).is(":checked");
				if(!chk){
					$(level2).prop('checked',false);
					$(level1).prop('checked',false);
				}else{
					var thislevel = $(this).parent("label").parent("div").parent("td").find("input[type='checkbox']");
					var chklevel1 = true;
					$(thislevel).each(function(){					
						var chkThis = $(this).is(":checked") ? true : false;	
						if(!chkThis) { 
							chklevel1 = false; 
						}
					});	
					$(level2).prop('checked',chklevel1);					
					//check level1
					var thislevel = $(this).parent("label").parent("div").parent("td").parent("tr").parent("tbody").find("input[type='checkbox'].level3");
					var chklevel1 = true;
					$(thislevel).each(function(){					
						var chkThis = $(this).is(":checked") ? true : false;	
						if(!chkThis) { 
							chklevel1 = false; 
						}
					});	
					$(level1).prop('checked',chklevel1);	
				}
			});
         })
		 
      </script>
	  <script type="text/javascript">
		$(document).ready(function(){
			$("td.access").each(function(){
				var eLevel2 = $(this).prev("td").find("input[type='checkbox'].level2");
				var chkLevel2 = true;
				$(this).find('input[type="checkbox"]').each(function(){
					var thisCheck = $(this).is(":checked");		
					if(!thisCheck)
						chkLevel2 = false;
				});
				$(eLevel2).prop("checked",chkLevel2);
			});
			$("table.table").each(function(){
				var eLevel1 = $(this).find("input[type='checkbox'].level1");
				var chkLevel1 = true;
				$(this).find('input[type="checkbox"].level2').each(function(){
					var thisCheck = $(this).is(":checked");		
					if(!thisCheck)
						chkLevel1 = false;
				});
				$(eLevel1).prop("checked",chkLevel1);
			})
		})
	  </script>