<?php 
	$page_title = 'User';
	$page_function = 'List';
	$this->headTitle($page_title.' '.$page_function);
	//check access right
	$intUserType = $_SESSION['intUserType'];
	
	$intView = 0;
	$intAdd = 0;
	$intEdit = 0;
	$intDelete = 0;
	foreach($accessRight as $access):
		$intView  = (int)$access["intView"];
		$intAdd  = (int)$access["intAdd"];
		$intEdit  = (int)$access["intEdit"];
		$intDelete  = (int)$access["intDelete"];
	endforeach;
	
	
?>
<div class="row">
    <div id="breadcrumb" class="col-xs-12">
        <ol class="breadcrumb">
            <li><a href="<?php echo $this->basePath() ?>">Dashboard</a></li>
            <li><a href="<?php echo $this->basePath() ?>/entity-user/index"><?php echo $page_title; ?></a></li>
            <li><a href="#"><?php echo $page_function; ?></a></li>
        </ol>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
	<?php if( $intAdd == 1 ):?>
        <div class="toolbar">
            <div class="pull-right">
				
                <a id="addItem" class="btn-add btn btn-default" href="<?php echo $this->basePath() . "/entity-user/edit/id/0"; ?>">Add</a>
            </div>
            <div class="clearfix"></div>
        </div>
	<?php endif; ?>
        <div class="box">
            <div class="box-header">
                <div class="box-name">
                    <i class="fa fa-users"></i>
                    <span><?php echo $page_title.' '.$page_function; ?></span>
                </div>
                <div class="box-icons">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="expand-link">
                        <i class="fa fa-expand"></i>
                    </a>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
                <div class="no-move"></div>
            </div>
			
            <div class="box-content no-padding">
                <table class="table table-bordered table-striped table-hover table-heading table-datatable" id="datatable-1">
                    <thead>
                        <tr>
                            <th>User Name</th>
							<th>Name</th>
						    <th>Email</th>
						    <th></th>
                        </tr>
                    </thead>
                    <tbody>
                	<!-- Start: list_row -->
                	<?php foreach($data as $item) : ?>
						<tr class="table-body">						    
						    <td class="table-body-row name column-left">
								<a  rel="tooltip" data-placement="top" data-original-title=" Edit " href="<?php echo $this->url('home/default', array('controller'=>'entity-user','action' => 'edit', 'id' => $item["idUser"] )) ?>">
									<?php echo $this->escapeHtml($item["strLoginId"]);?>
								</a>
							</td>
							<td class="table-body-row name column-left"><?php echo $this->escapeHtml($item["strName"]);?></td>
							<td class="table-body-row name column-left"><?php echo $this->escapeHtml($item["strEmail"]);?></td>
						    <td class="table-body-row last-column">
						    	<div class="btn-group btn-control"> 
									<?php if( $intEdit == 1 ):?>
	                                <a class="btn btn-default edit" rel="tooltip" data-placement="top" data-original-title=" Edit " href="<?php echo $this->url('home/default', array('controller'=>'entity-user','action' => 'edit', 'id' => $item["idUser"] )) ?>">
	                                    Edit
	                                </a>
									<?php endif; ?>
									<?php if( (int)$intDelete == 1 || (int)$intUserType == 0 || (int)$intUserType == 1):?>
										<a class="btn btn-default delete" rel="tooltip" data-placement="top" data-original-title=" Delete " href="<?php echo $this->url('home/default', array('controller'=>'entity-user','action' => 'delete', 'id' => $item["idUser"] )) ?>">Delete
										</a>
									<?php endif; ?>
	                            </div>
						    </td>
						</tr>
					<?php endforeach; ?>
                    <!-- End: list_row -->
                    </tbody>
                    <tfoot>
                        <tr>
							<th>User Name</th>
							<th>Name</th>
						    <th>Email</th>
						    <th></th>
                        </tr>
                    </tfoot>
                </table>
                </div>
        </div>
    </div>
</div>


<div class="clear"></div>

<script type="text/javascript">
// Run Datables plugin and create 3 variants of settings
function AllTables(){
    TestTable1();
    LoadSelect2Script(MakeSelect2);
}
function MakeSelect2(){
    $('select').select2();
    $('.dataTables_filter').each(function(){
        $(this).find('label input[type=text]').attr('placeholder', 'Search');
    });
}
$(document).ready(function() {
    // Load Datatables and run plugin on tables 
    LoadDataTablesScripts(AllTables);
    // Add Drag-n-Drop feature
    WinMove();
});
</script>